# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /categories/随笔
  红名之路: /categories/红名之路
  Algorithm: /categories/Algorithm
  Tech: /categories/Tech


# SubNav
subnav:
  github: "https://github.com/teveillan"
  #weibo: "#"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:teveillan@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml
sitemap: /sitemap.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: "UA-75903760-1"
favicon: /favicon.png

#你的头像url
avatar: "http://7tszmu.com1.z0.glb.clouddn.com/teveillan.jpg"

#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: teveillan
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
    Pira-黄大神: http://darkrhythm.net/
    Litten: http://litten.github.io/
    Yifan: http://www.zhuoyifan.net/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
