# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /categories/随笔
  红名之路: /categories/红名之路
  Algorithm: /categories/Algorithm
  Tech: /categories/Tech

# SubNav
subnav:
  github: "https://github.com/teveillan"
  #weibo: "#"
  rss: "/atom.xml"
  mail: "mailto:teveillan@gmail.com"
  # facebook: "#"
  # google: "mailto:teveillan@gmail.com"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml
sitemap: /sitemap.xml
# Content
excerpt_link: more
fancybox: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像
avatar: "http://7tszmu.com1.z0.glb.clouddn.com/teveillan.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: teveillan
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: true
#开启——
friends:
    Pira-黄大神: http://darkrhythm.net/
    Litten: http://litten.github.io/
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
